[tool.poetry]
name = "dxdy-pro"
version = "0.1.0"
description = ""
authors = ["Aamir Vazir <aamir.vazir@icloud.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
textual = "^2.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
